const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const API_BASE=(window.SOMENAI_API_BASE||'').replace(/\/$/,'');
let authToken=localStorage.getItem('somenai-token')||'',chats=[],current=null,conversation=[],busy=false,register=false,config,usageState,settings={studyMode:0,webMode:'auto'},quality=localStorage.getItem('somenai-quality')||'normal',imageMode=false;
const qualityInfo={low:{label:'低',model:'Llama',color:'green'},normal:{label:'中',model:'Qwen',color:'blue'},high:{label:'高',model:'Gemini',color:'purple'}};
const notice=s=>$('#notice').textContent=s||'';
async function api(path,method='GET',data){const headers={};if(data)headers['Content-Type']='application/json';if(authToken)headers.Authorization='Bearer '+authToken;let res;try{res=await fetch(API_BASE+'/api'+path,{method,headers,body:data?JSON.stringify(data):undefined});}catch{throw new Error('somenAIサーバーに接続できません。');}let value={};try{value=await res.json();}catch{}if(!res.ok){if(res.status===401&&!['/login','/register'].includes(path)){authToken='';localStorage.removeItem('somenai-token');if(!$('#auth').open)$('#auth').showModal();}throw new Error(value.error||`通信エラー（${res.status}）`);}return value;}
const safe=fn=>(...args)=>{try{return Promise.resolve(fn(...args)).catch(e=>notice(e.message));}catch(e){notice(e.message);}};
function closePopovers(except){for(const el of $('.menu-card'))if(el!==except)el.hidden=true;}
function updateModel(){const q=qualityInfo[quality];if(usageState)$('#usageTiny').textContent=usageState.items[quality].remaining;$('#modelName').textContent=`somenAI ${q.label}`;$$('[data-quality]').forEach(b=>b.classList.toggle('selected',b.dataset.quality===quality));}
function renderUsage(){if(!usageState)return;$('#usageTiny').textContent=usageState.items[quality].remaining;const names={low:'🟢 低 · Llama',normal:'🔵 中 · Qwen',high:'🟣 高 · Gemini',image:'🎨 画像生成'};for(const k of ['low','normal','high'])$('#left'+(k==='normal'?'Normal':k[0].toUpperCase()+k.slice(1))).textContent=`残り ${usageState.items[k].remaining}`;$('#usageCards').replaceChildren(...Object.entries(usageState.items).map(([k,v])=>{const d=document.createElement('div');d.className='usage-card';const s=document.createElement('small'),strong=document.createElement('strong');s.textContent=names[k];strong.textContent=`残り ${v.remaining} / ${v.limit}回`;d.append(s,strong);return d;}));}
async function refreshUsage(){usageState=await api('/usage');renderUsage();}
function renderHistory(){const nav=$('#history');nav.replaceChildren();const term=$('#search').value.trim().toLowerCase();const list=chats.filter(c=>c.title.toLowerCase().includes(term));for(const c of list){const b=document.createElement('button');b.textContent=c.title;b.className=c.id===current?'active':'';b.disabled=busy;b.onclick=safe(()=>openChat(c.id));nav.append(b);}if(!list.length){const p=document.createElement('p');p.textContent=term?'見つかりません':'会話はここに表示されます';nav.append(p);}}
async function refresh(){chats=await api('/chats');renderHistory();$('#chatTitle').textContent=chats.find(c=>c.id===current)?.title||'新しいチャット';}
function inline(el,text){const parts=text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);for(const p of parts){if(p.startsWith('**')&&p.endsWith('**')){const n=document.createElement('strong');n.textContent=p.slice(2,-2);el.append(n);}else if(p.startsWith('`')&&p.endsWith('`')){const n=document.createElement('code');n.textContent=p.slice(1,-1);el.append(n);}else el.append(document.createTextNode(p));}}
function tableNode(lines){const table=document.createElement('table');lines.filter((_,i)=>i!==1).forEach((line,i)=>{const tr=document.createElement('tr');line.replace(/^\||\|$/g,'').split('|').forEach(cell=>{const el=document.createElement(i?'td':'th');inline(el,cell.trim());tr.append(el);});table.append(tr);});return table;}
function chartNode(raw){const box=document.createElement('div');box.className='chart';try{const d=JSON.parse(raw);const title=document.createElement('strong');title.textContent=d.title||'グラフ';box.append(title);const max=Math.max(...d.values,1);d.labels.forEach((label,i)=>{const row=document.createElement('div');row.style.cssText='display:grid;grid-template-columns:90px 1fr 45px;gap:8px;align-items:center;margin:8px 0;font-size:12px';const l=document.createElement('span'),track=document.createElement('span'),bar=document.createElement('i'),v=document.createElement('b');l.textContent=label;track.style.cssText='height:12px;background:var(--hover);border-radius:6px;overflow:hidden';bar.style.cssText=`display:block;height:100%;width:${Math.max(2,d.values[i]/max*100)}%;background:#4385f5;border-radius:6px`;v.textContent=d.values[i];track.append(bar);row.append(l,track,v);box.append(row);});}catch{const pre=document.createElement('pre');pre.textContent=raw;box.append(pre);}return box;}
function format(target,text){target.replaceChildren();const blocks=text.split(/```/);blocks.forEach((block,bi)=>{if(bi%2){const first=block.indexOf('\n'),lang=first>=0?block.slice(0,first).trim():'',code=first>=0?block.slice(first+1):block;if(lang==='chart')target.append(chartNode(code));else{const pre=document.createElement('pre'),c=document.createElement('code');c.textContent=code;pre.append(c);target.append(pre);}return;}const lines=block.split('\n');for(let i=0;i<lines.length;){if(lines[i].includes('|')&&lines[i+1]&&/^\s*\|?\s*:?-+/.test(lines[i+1])){const group=[lines[i],lines[i+1]];i+=2;while(i<lines.length&&lines[i].includes('|'))group.push(lines[i++]);target.append(tableNode(group));continue;}const line=lines[i++];if(!line.trim())continue;const h=line.match(/^#{1,4}\s+(.+)/);const quote=line.match(/^>\s?(.+)/);const el=document.createElement(h?'h3':quote?'blockquote':'p');inline(el,h?h[1]:quote?quote[1]:line);target.append(el);}});}
function sourcesNode(items){const wrap=document.createElement('div');wrap.className='sources';const title=document.createElement('strong');title.textContent='参照元';const grid=document.createElement('div');grid.className='source-grid';for(const s of items){const a=document.createElement('a');a.className='source-card';if(!/^https?:\/\//i.test(s.url||''))continue;a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=s.title||s.url;grid.append(a);}wrap.append(title,grid);return wrap;}
function messageNode(m,index){const article=document.createElement('article');article.className='message '+m.role;const bubble=document.createElement('div');bubble.className='bubble';if(m.role==='assistant'){const who=document.createElement('div');who.className='who';const logo=document.createElement('span');logo.className='mini-logo';logo.textContent='S';const label=document.createElement('span');label.textContent=`somenAI · ${m.model||'回答中'}${m.status==='interrupted'?' · 中断':''}`;who.append(logo,label);article.append(who);}const content=document.createElement('div');content.className='content';if(m.image){const img=document.createElement('img');img.className='generated-image';img.src=m.image;img.alt=m.content;content.append(img);const p=document.createElement('p');p.textContent=m.content;content.append(p);}else format(content,m.content||'');for(const asset of m.assets||[]){const holder=document.createElement('div');holder.className='asset-holder';holder.textContent=asset.name;content.append(holder);loadMedia(asset,holder);}bubble.append(content);if(m.sources?.length)bubble.append(sourcesNode(m.sources));article.append(bubble);if(m.role==='assistant'&&(m.content||m.image)){const tools=document.createElement('div');tools.className='message-tools';const copy=document.createElement('button');copy.textContent='コピー';copy.onclick=safe(async()=>{await navigator.clipboard.writeText(m.content);copy.textContent='コピー済み';});tools.append(copy);if(index===conversation.length-1&&!m.image){const retry=document.createElement('button');retry.textContent='↻ 再生成';retry.disabled=busy;retry.onclick=safe(()=>send(true));tools.append(retry);}article.append(tools);}return article;}
function render(){const area=$('#messages');area.replaceChildren(...conversation.map(messageNode));$('#welcome').hidden=conversation.length>0;for(const id of ['rename','delete','export'])$('#'+id).disabled=!current||busy;}
function setBusy(v){busy=v;$('#messages').setAttribute('aria-busy',String(v));$('#send').hidden=v;$('#stop').hidden=!v;$('#prompt').disabled=v;$('#newChat').disabled=v;renderHistory();render();}
async function openChat(id){if(busy)return;pendingAssets=[];renderPending();const c=await api('/chats/'+id);current=id;conversation=c.messages;notice();render();renderHistory();$('#chatTitle').textContent=c.title;document.body.classList.remove('sidebar-open');$('#messages').scrollTop=$('#messages').scrollHeight;}
function newChat(){if(busy)return;pendingAssets=[];renderPending();current=null;conversation=[];$('#chatTitle').textContent='新しいチャット';render();renderHistory();notice();$('#prompt').focus();document.body.classList.remove('sidebar-open');}
async function oldGenerateImage(){const prompt=$('#prompt').value.trim();if(!prompt)return;setBusy(true);notice();conversation.push({role:'user',content:prompt});$('#prompt').value='';render();const waiting={role:'assistant',content:'画像を生成しています…',model:'Cloudflare AI'};conversation.push(waiting);render();try{const result=await api('/images','POST',{prompt});waiting.content=prompt;waiting.image=result.image;}catch(e){conversation.pop();notice(e.message);}finally{setBusy(false);await refreshUsage();render();}}
async function send(regenerate=false){if(busy)return;if(imageMode&&!regenerate)return generateImage();const content=$('#prompt').value.trim();if(!regenerate&&!content)return;notice();if(!current){current=(await api('/chats','POST',{})).id;await refresh();}const id=current;setBusy(true);let started=false,answer,sources=[];$('#toolStatus').hidden=true;try{const res=await fetch(`${API_BASE}/api/chats/${id}/generate`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+authToken},body:JSON.stringify({content,regenerate,quality,assets:pendingAssets.map(a=>a.id)})});if(!res.ok){const b=await res.json();throw new Error(b.error);}const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(!line)continue;const event=JSON.parse(line);if(event.type==='start'){started=true;if(regenerate){while(conversation.at(-1)?.role==='assistant')conversation.pop();}else{conversation.push({role:'user',content,assets:pendingAssets});pendingAssets=[];renderPending();$('#prompt').value='';}answer={role:'assistant',content:'',model:event.model,sources:[]};conversation.push(answer);render();}if(event.type==='tool'){$('#toolStatus').hidden=false;$('#toolStatus').textContent=(event.name==='web_search'?'🔎 ':event.name==='schoollink_search'?'🏫 ':'')+event.label;}if(event.type==='delta'){answer.content+=event.text;const target=$('#messages').lastElementChild?.querySelector('.content');if(target)format(target,answer.content);const pane=$('#messages');if(pane.scrollHeight-pane.scrollTop-pane.clientHeight<180)pane.scrollTop=pane.scrollHeight;}if(event.type==='sources'){sources=event.items;answer.sources=sources;render();}if(event.type==='error')notice(event.message);}}}catch(e){notice(e.message||'通信に失敗しました。');}finally{$('#toolStatus').hidden=true;setBusy(false);try{if(started){const latest=await api('/chats/'+id);conversation=latest.messages;if(sources.length&&conversation.at(-1))conversation.at(-1).sources=sources;}await Promise.all([refresh(),refreshUsage()]);render();}catch(e){notice(e.message);}$('#prompt').focus();}}
function toggleImage(force){imageMode=force??!imageMode;$('#imageMode').classList.toggle('active',imageMode);$('#modeLabel').textContent=imageMode?'画像生成モード':'';$('#prompt').placeholder=imageMode?'作りたい画像を説明してください':'somenAI にメッセージを送信';$('#prompt').focus();}
$('#composer').onsubmit=safe(e=>{e.preventDefault();return send();});$('#prompt').oninput=e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,180)+'px';};$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!matchMedia('(pointer: coarse)').matches){e.preventDefault();safe(()=>send())();}};
$('#modelButton').onclick=e=>{e.stopPropagation();const m=$('#modelMenu');closePopovers(m);m.hidden=!m.hidden;};$$('[data-quality]').forEach(b=>b.onclick=()=>{quality=b.dataset.quality;localStorage.setItem('somenai-quality',quality);updateModel();$('#modelMenu').hidden=true;});$('#moreButton').onclick=e=>{e.stopPropagation();const m=$('#moreMenu');closePopovers(m);m.hidden=!m.hidden;};document.addEventListener('click',()=>closePopovers());
$('#newChat').onclick=newChat;$('#search').oninput=renderHistory;$('#stop').onclick=safe(()=>api('/chats/'+current+'/stop','POST',{}));$('#menu').onclick=()=>document.body.classList.add('sidebar-open');$('#closeSide').onclick=$('#scrim').onclick=()=>document.body.classList.remove('sidebar-open');
$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('somenai-theme',document.body.classList.contains('dark')?'dark':'light');};document.body.classList.remove('dark');
$('#settingsOpen').onclick=safe(async()=>{$('#settingsDialog').showModal();settings=await api('/settings');await refreshUsage();$('#studyMode').checked=!!settings.studyMode;$$('[data-web]').forEach(b=>b.classList.toggle('active',b.dataset.web===settings.webMode));$('#settingsDialog').showModal();});$('#usageButton').onclick=()=>$('#settingsOpen').click();$('#settingsClose').onclick=()=>$('#settingsDialog').close();$('#studyMode').onchange=safe(async e=>{settings=await api('/settings','PATCH',{studyMode:e.target.checked});});$$('[data-web]').forEach(b=>b.onclick=safe(async()=>{settings=await api('/settings','PATCH',{webMode:b.dataset.web});$$('[data-web]').forEach(x=>x.classList.toggle('active',x.dataset.web===settings.webMode));}));
$('#imageMode').onclick=()=>toggleImage();$('#imageSuggestion').onclick=()=>toggleImage(true);$$('[data-prompt]').forEach(b=>b.onclick=()=>{$('#prompt').value=b.dataset.prompt;$('#prompt').focus();});
$('#rename').onclick=()=>{$('#editTitle').value=chats.find(c=>c.id===current)?.title||'';$('#editDialog').showModal();};$('#editCancel').onclick=()=>$('#editDialog').close();$('#editForm').onsubmit=safe(async e=>{e.preventDefault();await api('/chats/'+current,'PATCH',{title:$('#editTitle').value});$('#editDialog').close();await refresh();});$('#delete').onclick=()=>$('#deleteDialog').showModal();$('#deleteCancel').onclick=()=>$('#deleteDialog').close();$('#deleteConfirm').onclick=safe(async()=>{await api('/chats/'+current,'DELETE');$('#deleteDialog').close();newChat();await refresh();});$('#export').onclick=()=>{const title=chats.find(c=>c.id===current)?.title||'chat';const blob=new Blob([`# ${title}\n\n`+conversation.map(m=>`## ${m.role==='user'?'あなた':'somenAI'}\n\n${m.content}`).join('\n\n')],{type:'text/markdown;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=title.replace(/[^\p{L}\p{N}_-]/gu,'_').slice(0,50)+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#logout').onclick=safe(async()=>{await api('/logout','POST',{});authToken='';localStorage.removeItem('somenai-token');current=null;chats=[];conversation=[];render();renderHistory();$('#username').textContent='ゲスト';$('#auth').showModal();});$('#auth').addEventListener('cancel',e=>e.preventDefault());$('#authToggle').onclick=()=>{register=!register;$('#authTitle').textContent=register?'アカウントを作成':'somenAIへログイン';$('#authSubmit').textContent=register?'登録する':'ログイン';$('#authToggle').textContent=register?'ログインに戻る':'新規登録';$('#inviteLabel').hidden=!register;$('#authError').textContent='';};$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';$('#authSubmit').disabled=true;try{const u=await api(register?'/register':'/login','POST',{name:$('#name').value,password:$('#password').value,invite:$('#invite').value});authToken=u.token;localStorage.setItem('somenai-token',authToken);$('#username').textContent=u.name;$('#avatar').textContent=u.name.slice(0,1).toUpperCase();$('#auth').close();$('#password').value='';await loadUser();}catch(e){$('#authError').textContent=e.message;}finally{$('#authSubmit').disabled=false;}};
async function loadUser(){const [u,c,s,use]=await Promise.all([api('/me'),api('/chats'),api('/settings'),api('/usage')]);chats=c;settings=s;applyAppearance(s.appearance||{});usageState=use;$('#username').textContent=u.name;$('#avatar').textContent=u.name.slice(0,1).toUpperCase();renderHistory();renderUsage();}
async function init(){updateModel();try{if(!API_BASE.startsWith('https://'))throw new Error('API接続先をconfig.jsに設定してください。');config=await api('/config');$('#authToggle').hidden=!config.registration;const tools=[['🔎 Web検索',config.tools.web],['🏫 SchoolLink',config.tools.schoolLink],['🎨 画像生成',config.tools.image],['🧮 計算','ready']];$('#toolReadiness').replaceChildren(...tools.map(([name,ready])=>{const d=document.createElement('div');d.className='tool-item';const a=document.createElement('span'),b=document.createElement('span');a.textContent=name;b.className=ready?'ready':'pending';b.textContent=ready?'利用可能':'未設定';d.append(a,b);return d;}));if(authToken){try{await loadUser();}catch{if(!$('#auth').open)$('#auth').showModal();}}else $('#auth').showModal();render();}catch(e){notice(e.message);}}

let pendingAssets=[];
function renderPending(){const box=$('#pendingFiles');box.hidden=!pendingAssets.length;box.replaceChildren(...pendingAssets.map(a=>{const b=document.createElement('button');b.textContent=a.name+' ×';b.onclick=()=>{pendingAssets=pendingAssets.filter(x=>x.id!==a.id);renderPending();};return b;}));}
async function loadMedia(asset,holder){
 try{const r=await fetch(API_BASE+'/api/media/'+asset.id,{headers:{Authorization:'Bearer '+authToken}});if(!r.ok)throw Error('ファイルを取得できません');const blob=await r.blob(),url=URL.createObjectURL(blob);const el=document.createElement(asset.mime.startsWith('image/')?'img':'a');if(el.tagName==='IMG'){el.src=url;el.alt=asset.name;el.className='generated-image';el.onload=()=>URL.revokeObjectURL(url);}else{el.href=url;el.download=asset.name;el.textContent='↓ '+asset.name;el.addEventListener('click',()=>setTimeout(()=>URL.revokeObjectURL(url),1000),{once:true});}holder.replaceChildren(el);}catch{holder.textContent='ファイルを読み込めませんでした';}
}
$('#fileInput').onchange=safe(async e=>{
 const files=[...e.target.files];if(files.length+pendingAssets.length>4)throw Error('添付は4件までです。');
 if(!current){current=(await api('/chats','POST',{})).id;await refresh();}
 for(const f of files){if(f.size>10*1024*1024)throw Error('添付は1件10MBまでです。');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});const result=await api('/chats/'+current+'/uploads','POST',{name:f.name,data});pendingAssets.push(result.asset);renderPending();}
 e.target.value='';notice('ファイルは保存されました。現在、添付の内容解析は未対応です。');
});
async function generateImage(){
 const prompt=$('#prompt').value.trim();if(!prompt)return;if(!current){current=(await api('/chats','POST',{})).id;await refresh();}
 setBusy(true);$('#toolStatus').hidden=false;$('#toolStatus').textContent='画像を生成しています…';
 try{await api('/images','POST',{prompt,chatId:current});$('#prompt').value='';conversation=(await api('/chats/'+current)).messages;await refresh();await refreshUsage();}finally{$('#toolStatus').hidden=true;setBusy(false);}
}
function applyAppearance(v){
 document.body.classList.toggle('dark',v.theme==='dark');document.body.dataset.accent=['ink','blue','mint','violet','coral'].includes(v.accent)?v.accent:'ink';document.body.dataset.composer=['auto','blue','mint','violet','coral'].includes(v.composer)?v.composer:'auto';
 $('[data-accent]').filter(x=>x.tagName==='BUTTON').forEach(b=>b.setAttribute('aria-pressed',b.dataset.accent===document.body.dataset.accent));
 $('[data-composer]').filter(x=>x.tagName==='BUTTON').forEach(b=>b.setAttribute('aria-pressed',b.dataset.composer===document.body.dataset.composer));
}
async function appearanceChange(change){const next={...(settings.appearance||{}),...change};applyAppearance(next);settings.appearance=next;if(authToken)settings=await api('/settings','PATCH',{appearance:next});}
$('#themeToggle').onclick=safe(()=>appearanceChange({theme:document.body.classList.contains('dark')?'light':'dark'}));
$('#accentPicker button').forEach(b=>b.onclick=safe(()=>appearanceChange({accent:b.dataset.accent})));
$('#composerPicker button').forEach(b=>b.onclick=safe(()=>appearanceChange({composer:b.dataset.composer})));
function viewport(){document.documentElement.style.setProperty('--vh',(window.visualViewport?.height||innerHeight)+'px');}
window.visualViewport?.addEventListener('resize',viewport);viewport();
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();newChat();}if(e.key==='Escape'){document.body.classList.remove('sidebar-open');closePopovers();}});
applyAppearance({});
init();
