const $=s=>document.querySelector(s);
const API_BASE=(window.SOMENAI_API_BASE||'').replace(/\/$/,'');
let authToken=localStorage.getItem('somenai-token')||'';
let chats=[],current=null,conversation=[],busy=false,register=false,config;
const notice=s=>$('#notice').textContent=s;
async function api(path,method='GET',data){const headers={};if(data)headers['Content-Type']='application/json';if(authToken)headers.Authorization='Bearer '+authToken;const res=await fetch(API_BASE+'/api'+path,{method,headers,body:data?JSON.stringify(data):undefined});const value=await res.json();if(!res.ok){if(res.status===401&&!['/login','/register'].includes(path)){authToken='';localStorage.removeItem('somenai-token');if(!$('#auth').open)$('#auth').showModal();}throw new Error(value.error);}return value;}
const safe=fn=>(...args)=>{try{return Promise.resolve(fn(...args)).catch(e=>notice(e.message));}catch(e){notice(e.message);}};
function renderHistory(){const nav=$('#history');nav.replaceChildren();const term=$('#search').value.toLowerCase();for(const c of chats.filter(c=>c.title.toLowerCase().includes(term))){const b=document.createElement('button');b.textContent='◌  '+c.title;b.className=c.id===current?'active':'';b.disabled=busy;b.onclick=safe(()=>openChat(c.id));nav.append(b);}if(!nav.children.length){const p=document.createElement('p');p.textContent=term?'見つかりませんでした':'ここに会話が増えていきます。';nav.append(p);}}
async function refresh(){chats=await api('/chats');renderHistory();$('#chatTitle').textContent=chats.find(c=>c.id===current)?.title||'新しいチャット';}
function format(target,text){target.replaceChildren();const pieces=text.split(/```/);pieces.forEach((piece,i)=>{if(i%2){const pre=document.createElement('pre'),code=document.createElement('code');code.textContent=piece.replace(/^[a-zA-Z0-9_+-]*\n/,'');pre.append(code);target.append(pre);}else{for(const line of piece.split('\n')){const h=line.match(/^#{1,4}\s+(.+)/);const el=document.createElement(h?'h3':'span');const parts=(h?h[1]:line+'\n').split(/(\*\*[^*]+\*\*|`[^`]+`)/g);parts.forEach(p=>{const type=p.startsWith('**')?'strong':p.startsWith('`')?'code':null; if(type){const node=document.createElement(type);node.textContent=p.slice(type==='strong'?2:1,type==='strong'?-2:-1);el.append(node);}else el.append(document.createTextNode(p));});target.append(el);}}});}
function messageNode(m,index){const article=document.createElement('article');article.className='message '+m.role;const meta=document.createElement('div');meta.className='meta';meta.textContent=m.role==='user'?'あなた':`somenAI · ${m.model||'回答を準備中'}${m.status==='interrupted'?' · 中断':''}`;const content=document.createElement('div');content.className='content';format(content,m.content);article.append(meta,content);if(m.role==='assistant'&&m.content){const actions=document.createElement('div');actions.className='tools';const copy=document.createElement('button');copy.textContent='コピー';copy.onclick=safe(async()=>{await navigator.clipboard.writeText(m.content);copy.textContent='コピーしました';});actions.append(copy);if(index===conversation.length-1){const retry=document.createElement('button');retry.textContent='↻ 再生成';retry.disabled=busy;retry.onclick=safe(()=>send(true));actions.append(retry);}article.append(actions);}return article;}
function render(){const area=$('#messages');area.replaceChildren(...conversation.map(messageNode));$('#welcome').hidden=conversation.length>0;['rename','delete','export'].forEach(id=>$('#'+id).disabled=!current||busy);}
function setBusy(v){busy=v;$('#messages').setAttribute('aria-busy',String(v));$('#send').hidden=v;$('#stop').hidden=!v;$('#prompt').disabled=v;$('#quality').disabled=v;$('#new').disabled=v;$('#logout').disabled=v;renderHistory();render();}
async function openChat(id){if(busy)return;const c=await api('/chats/'+id);current=id;conversation=c.messages;notice('');render();renderHistory();$('#chatTitle').textContent=c.title;document.body.classList.remove('sidebar-open');}
function newChat(){if(busy)return;current=null;conversation=[];$('#chatTitle').textContent='新しいチャット';render();renderHistory();notice('');$('#prompt').focus();document.body.classList.remove('sidebar-open');}
async function send(regenerate=false){if(busy)return;const content=$('#prompt').value.trim();if(!regenerate&&!content)return;notice('');if(!current){current=(await api('/chats','POST',{})).id;await refresh();}
 const id=current;setBusy(true);let started=false;
 try{const res=await fetch(`${API_BASE}/api/chats/${id}/generate`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+authToken},body:JSON.stringify({content,regenerate,quality:$('#quality').value})});if(!res.ok){const b=await res.json();throw new Error(b.error);}const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='',answer;
 while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(!line)continue;const event=JSON.parse(line);if(event.type==='start'){started=true;if(regenerate){while(conversation.at(-1)?.role==='assistant')conversation.pop();}else{conversation.push({role:'user',content});$('#prompt').value='';}answer={role:'assistant',content:'',model:event.model};conversation.push(answer);render();}if(event.type==='delta'){answer.content+=event.text;const target=$('#messages').lastElementChild?.querySelector('.content');if(target)format(target,answer.content);const nearBottom=window.innerHeight+window.scrollY>=document.body.scrollHeight-220;if(nearBottom)window.scrollTo({top:document.body.scrollHeight,behavior:'instant'});}if(event.type==='error')notice(event.message);}}
 }catch(e){notice(e.message||'通信に失敗しました。');}finally{setBusy(false);try{if(started)conversation=(await api('/chats/'+id)).messages;await refresh();render();}catch(e){notice(e.message);}$('#prompt').focus();}}
$('#composer').onsubmit=safe(e=>{e.preventDefault();return send();});
$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!matchMedia('(pointer: coarse)').matches){e.preventDefault();safe(()=>send())();}};
$('#new').onclick=newChat;$('#search').oninput=renderHistory;
$('#stop').onclick=safe(()=>api('/chats/'+current+'/stop','POST',{}));
$('#menu').onclick=()=>document.body.classList.toggle('sidebar-open');
document.querySelector('main').addEventListener('click',e=>{if(!e.target.closest('#menu'))document.body.classList.remove('sidebar-open');});
$('#theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('somenai-theme',document.body.classList.contains('light')?'light':'dark');};
if(localStorage.getItem('somenai-theme')==='light')document.body.classList.add('light');
$('#rename').onclick=()=>{$('#editTitle').value=chats.find(c=>c.id===current)?.title||'';$('#editDialog').showModal();};
$('#editCancel').onclick=()=>$('#editDialog').close();$('#editForm').onsubmit=safe(async e=>{e.preventDefault();await api('/chats/'+current,'PATCH',{title:$('#editTitle').value});$('#editDialog').close();await refresh();});
$('#delete').onclick=()=>$('#deleteDialog').showModal();$('#deleteCancel').onclick=()=>$('#deleteDialog').close();$('#deleteConfirm').onclick=safe(async()=>{await api('/chats/'+current,'DELETE');$('#deleteDialog').close();newChat();await refresh();});
$('#export').onclick=()=>{const title=chats.find(c=>c.id===current)?.title||'chat';const blob=new Blob([`# ${title}\n\n`+conversation.map(m=>`## ${m.role==='user'?'あなた':'somenAI'}\n\n${m.content}`).join('\n\n')],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=title.replace(/[^\p{L}\p{N}_-]/gu,'_').slice(0,50)+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#logout').onclick=safe(async()=>{await api('/logout','POST',{});authToken='';localStorage.removeItem('somenai-token');current=null;chats=[];conversation=[];render();renderHistory();$('#username').textContent='ゲスト';$('#password').value='';$('#auth').showModal();});
$('#auth').addEventListener('cancel',e=>e.preventDefault());
$('#authToggle').onclick=()=>{register=!register;$('#authTitle').textContent=register?'はじめまして。':'おかえりなさい。';$('#authSubmit').textContent=register?'アカウントを作成':'ログイン';$('#authToggle').textContent=register?'アカウントをお持ちの方 · ログイン':'はじめての方はこちら · 新規登録';$('#inviteLabel').hidden=!register;$('#password').autocomplete=register?'new-password':'current-password';$('#authError').textContent='';};
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';$('#authSubmit').disabled=true;try{const u=await api(register?'/register':'/login','POST',{name:$('#name').value,password:$('#password').value,invite:$('#invite').value});authToken=u.token;localStorage.setItem('somenai-token',authToken);$('#username').textContent=u.name;$('#auth').close();$('#password').value='';await refresh();}catch(e){$('#authError').textContent=e.message;}finally{$('#authSubmit').disabled=false;}};
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#prompt').value=b.dataset.prompt;$('#prompt').focus();});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();if(!$('#auth').open)newChat();}});
async function init(){try{if(!API_BASE.startsWith('https://'))throw new Error('APIの接続先が設定されていません。config.jsを確認してください。');config=await api('/config');$('#authToggle').hidden=!config.registration;for(const option of $('#quality').options){if(!config.tiers[option.value].ready)option.textContent+='（未設定）';}try{const u=await api('/me');$('#username').textContent=u.name;await refresh();}catch{if(!$('#auth').open)$('#auth').showModal();}render();}catch(e){notice(e.message);}}
init();
